foodtracker/models.py
from enum import unique
from .extensions import db

log_food =db.Table('log_food'
   log_id= db.Column('log_id',db.Integer,db.ForeignKey('log.id'),primary_key = True) 
   food_id= db.Column('food_id',db.Integer,db.ForeignKey('food.id'),primary_key = True) 
)

class Food(db.Model):
    id= db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(50),unique = True, nullable = False)
    proteins = db.Column(db.Integer, nullable = False)
    carbs = db.Column(db.Integer, nullable = False)
    fats = db.Column(db.Integer, nullable = False)

class Log(db.Model):
    id= db.Column(db.Integer,primary_key = True)
    date = db.Column(db.Date, nullable = False)
    foods = db.relationship('Food',secondary=log_food)

foodtracker/__init__.py
from flask import *
import pyrebase


from .main.routes import main
#from .extensions import db
def create_app():
    app = Flask(__name__)

    #app.config['SQLALCHEMY_DATABASE_URI' ] = 'sqlite:///db.sqlite3'
    #app.config['SQLALCHEMY_TRACK_MODIFICATIONS' ] = False
    #db.init_app(app)
    app.register_blueprint(main)
    return app

foodtracker/main/routes.py
from flask import *
import googletrans 
from googletrans import Translator
import pyrebase
import spoonacular as sp
import random
import requests
import json


config = {
   "apiKey" : "AIzaSyA4av3lN5gUTSXLSMuBQeigqOZuQiz5fjo",
    "authDomain": "pythontrial-151b6.firebaseapp.com",
    "databaseURL": "https://pythontrial-151b6-default-rtdb.firebaseio.com",
    "projectId": "pythontrial-151b6",
    "storageBucket": "pythontrial-151b6.appspot.com",
    "messagingSenderId": "749934275221",
    "appId": "1:749934275221:web:ff9e8d5201675414ff499c"
}
api = sp.API('c4e983e132c1412a9ab494902242598c')

firebase = pyrebase.initialize_app(config)

auth = firebase.auth()

storage = firebase.storage()

db = firebase.database()

main = Blueprint('main',__name__)

def call_API(foodName, apiKey):
    url = f'https://api.nal.usda.gov/fdc/v1/foods/search?query={foodName}&dataType=Branded&pageSize=25&pageNumber=2&sortBy=dataType.keyword&sortOrder=asc&brandOwner=Kar%20Nut%20Products%20Company&api_key=gjfigRBqjrJISugOEoF7O9E45ilS2jEUK4He5gjY'
    r = requests.get(url)
    print(r.status_code)  # 200
    
    ret = r.json()

    items= []
    for i in ret['foods']:

        lala = i['brandName']+" "
        lala+=i['brandOwner']+" "
        if('subbrandName' in i):
            lala+=i['subbrandName']+" "
         
        if(len(i['foodNutrients'])>0):
            lala+=str(i['foodNutrients'][0]['value'])+ "g protein"
        items.append(lala)

    # for i in (1,50):
    #     print(ret[i]['description'])
    #     print(ret[i]['brandOwner'])
    #     print(ret[i]['foodNutrients'][0]['amount']) #protein
    #     print(ret[i]['foodNutrients'][1]['amount']) #fat
    #     print(ret[i]['foodNutrients'][2]['amount']) #carbs
    #     print(ret[i]['foodNutrients'][4]['amount']) #kcal
    print(type(ret['foods']))
    print(len(ret['foods']))

    return items


@main.route('/', methods=['GET', 'POST']) #firebase
def index():
    uid='testcustomer'
    if request.method == 'POST' and request.form['submit'] == 'tuna':
        foodinfo = db.child("food").get().val()
        for val in foodinfo:
            if db.child("food").child(val).get().val()['foodName']=='Tuna roll':
               db.child("carts").child(uid).push(val)
    elif request.method == 'POST' and request.form['submit'] == 'blt':
        foodinfo = db.child("food").get().val()
        for val in foodinfo:
            if db.child("food").child(val).get().val()['foodName']=='BLT sandwich':
               db.child("carts").child(uid).push(val)
    return render_template('index.html', randtext="lalal")

@main.route('/protein', methods=['GET', 'POST'])
def protein():
    if request.method == 'POST':
        foodname = request.form['searchfood']
        ans = call_API(foodname, "gjfigRBqjrJISugOEoF7O9E45ilS2jEUK4He5gjY")
        return render_template('protein.html',randtext=foodname, listitems= ans)
    return render_template('protein.html')

@main.route('/add')
def add():
    return render_template('add.html')

@main.route('/onthebudget')
def budget():
    

    n = random.randint(1, 100)
    response = api.get_recipe_information(n)
    data = response.json()
    ings="Ingredients: \n"
    instructions ="Instructions: \n"

    if data['extendedIngredients']!=None:
        for ing in data['extendedIngredients']:
            ings+=ing['original']+"\n"

    if data['instructions']!=None:
        instructions+=data['instructions'].replace(".", "\n")

    return render_template('onthebudget.html', title =data['title'], link =data['image'],servings="Servings: "+str(data['servings']),preptime="Ready in "+str(data['readyInMinutes'])+" minutes", ingredients = ings, instructions=instructions)

@main.route('/view')
def view():
    return render_template('view.html')

@main.route('/login') 
def login():
    return render_template('login.html')

@main.route('/logincustomer', methods=['GET', 'POST']) #firebase
def logincustomer():
    unsuccessful = 'Login failed, email or password is incorrect!'
    successful = 'Login successful'
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['pass']
        try:
            auth.sign_in_with_email_and_password(email, password)
            return redirect(url_for('main.index'))
        except:
            return render_template('login_customer.html', us=unsuccessful)
    return render_template('login_customer.html')

@main.route('/loginvendor', methods=['GET', 'POST']) #firebase
def loginvendor():
    unsuccessful = 'Login failed, email or password is incorrect!'
    successful = 'Login successful'
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['pass']
        try:
            auth.sign_in_with_email_and_password(email, password)
            return redirect(url_for('main.orderlist'))
        except:
            return render_template('login_vendor.html', us=unsuccessful)

    return render_template('login_vendor.html')

@main.route('/loginadmin', methods=['GET', 'POST']) #firebase
def loginadmin():
    unsuccessful = 'Login failed, email or password is incorrect!'
    successful = 'Login successful'
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['pass']
        try:
            auth.sign_in_with_email_and_password(email, password)
            return redirect(url_for('main.adminview'))
        except:
            return render_template('login_admin.html', us=unsuccessful)

    return render_template('login_admin.html')

@main.route('/adminview')
def adminview():
    return render_template('adminView.html')

@main.route('/adminanalytics')
def adminanalytics():
    return render_template('adminAnalytics.html')
@main.route('/adminviewdeleted')
def adminviewdeleted():
    return render_template('adminViewDeleted.html')    

@main.route('/cart')
def cart():
    return render_template('cart.html')
    
@main.route('/checkout_cwl')
def checkout_cwl():
    return render_template('checkout_cwl.html')
    
@main.route('/checkout_card')
def checkout_card():
    return render_template('checkout_card.html')    

@main.route('/bill')
def bill():

    
    return render_template('bill.html')

@main.route('/orderlist')
def orderlist():
    return render_template('orderlist.html')

@main.route('/vendor_menu')
def vendor_menu():
    return render_template('vendor_menu.html')

@main.route('/vendor_analytics')
def vendor_analytics():
    return render_template('vendor_analytics.html')

@main.route('/vendorEmployee')
def vendorEmployee():
    return render_template('vendorEmployee.html')

foodtracker/templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='bs/css/united.min.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}"/>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

<div class="container-fluid" id="wrapper">

    <div class="row" id="homeJumbo">
        <div class="overlay"></div>
        <div class="col-lg-12">
            <h1>
                <a href="{{ url_for('main.index') }}">Your Cart</a>
            </h1>

            <div class="row t20">
                <div class="col-lg-4 col-lg-offset-4">
                    <ul class="nav nav-pills nav-justified">
                        <li role="presentation">
                            <a href="{{ url_for('main.index') }}" title="Home">Home</a>
                        </li>


                        <li role="presentation" class="active">
                            <a href="{{ url_for('main.cart') }}" title="Add Food Item"><i
                                    class="glyphicon glyphicon-shopping-cart"></i></a>
                        </li>
                        <li role="presentation">
                            <a href="{{ url_for('main.login') }}" title="Log out">Log out</a>
                        </li>
                    </ul>

                </div>


            </div>
        </div>
    </div>

    <div class="row t20">
        <div class="col-lg-8 col-lg-offset-2">
            <div class="panel panel-default">
                <div class="table-responsive">
                    <table class="table table-striped table-hover table-bordered">
                        <thead>
                        <tr>
                            <th style="width: 5%;">Item</th>
                            <th>Item Name</th>
                            <th style="width: 10%;">Quantity</th>
                            <th style="width: 10%;">Cost</th>
                            <th style="width: 20%;">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <!--Image-->
                                <div class="panel-body text-bold">
                                    <img src="{{ url_for('static', filename='img/sushi_tuna_roll.jpg') }}"
                                         alt="Responsive image" class="img-fluid">
                                </div>

                            </td>
                            <td>Tuna Roll</td>
                            <td>1</td>
                            <td>$14.39</td>
                            <td>
                                <a href="#" class="btn btn-danger btn-xs">
                                    <i class="glyphicon glyphicon-trash"></i> Delete
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="panel-body text-bold">
                                    <img src="{{ url_for('static', filename='img/well_blt.jpeg') }}"
                                         alt="Responsive image" class="img-fluid">
                                </div>
                            </td>
                            <td>BLT Sandwich</td>
                            <td>1</td>
                            <td>11.99</td>
                            <td>
                                <a href="#" class="btn btn-danger btn-xs">
                                    <i class="glyphicon glyphicon-trash"></i> Delete
                                </a>
                            </td>
                        </tr>

                        <tr>
                            <td>
                                <p class="h2"><b>
                                    <center>Total</center>
                                </b></p>
                            </td>
                            <td></td>
                            </td>
                            <td></td>
                            <td>
                                <b>$ 26.38</b></td>


                            <td>
                                </a>
                                <button style="background-color:#000080" class="btn btn-block">
                                    <a href="{{ url_for('main.checkout_cwl') }}" title="checkout">
                                        <p style="color:white">Pay with UBC Card</p>
                                    </a>
                                </button>
                                </a>

                                <br>

                                <a href="#">
                                    <!-- Replace "test" with your own sandbox Business account app client ID -->
                                    <script src="https://www.paypal.com/sdk/js?client-id=AUAhVIuGp7StB_rhF5j3juWNNy9eS7E2re_8M-lEWGasbKSu9RAHhUk15wGV1k2YM4AKwolwWhktI8T_&currency=CAD"></script>
                                    <!-- Set up a container element for the button -->
                                    <div id="paypal-button-container"></div>
                                    <script>
                                        paypal.Buttons({
                                            // Sets up the transaction when a payment button is clicked
                                            createOrder: (data, actions) => {
                                                return actions.order.create({
                                                    purchase_units: [{
                                                        amount: {
                                                            value: '26.38' // Can also reference a variable or function
                                                        }
                                                    }]
                                                });
                                            },
                                            // Finalize the transaction after payer approval
                                            onApprove: (data, actions) => {
                                                return actions.order.capture().then(function (orderData) {
                                                    // Successful capture! For dev/demo purposes:
                                                    console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
                                                    const transaction = orderData.purchase_units[0].payments.captures[0];
                                                    alert(`Transaction ${transaction.status}: ${transaction.id}\n\nSee console for all available details`);
                                                    // When ready to go live, remove the alert and show a success message within this page. For example:
                                                    const element = document.getElementById('paypal-button-container');
                                                	element.innerHTML = '<h3>Thank you for your payment!</h3>';
                                                    location.replace("/bill");
                                                });
                                            }
                                        }).render('#paypal-button-container');
                                    </script>
                                </a>
                                <br>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="{{ url_for('static', filename='/bs/js/jquery.min.js') }}"></script>
    <!-- Bootstrap JavaScript -->
    <script src="{{ url_for('static', filename='/bs/js/bootstrap.min.js') }}"></script>
</div>

</body>
</html>

foodtracker/templates/login.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Skip the line | Home</title>

		<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{url_for('static', filename='bs/css/united.min.css')}}" />
		<link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
        
		<div class="container-fluid" id="wrapper">

           
			
			<div class="row" id="homeJumbo">
				<div class="overlay"></div>
				<div class="col-lg-12">
					<h1>
						<a href="{{url_for('main.index')}}">UBC SUO: Skip the line</a>
					</h1>
					
					
				</div>
			</div>
            <div class="row t20">
				<div class="col-lg-4 col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body text-center">
							<h3 class="lean-h text-black">
								<i class="glyphicon glyphicon-user"></i> Choose User Type
							</h3>
							<hr />

								
								
                                <div class="row">
                                     <div class="col-lg-12">
                                        
                                        <label style="visibility:hidden">submit</label>
                                       <a href="{{url_for('main.logincustomer')}}"> <button href="{{url_for('main.index')}}"  class="btn btn-primary btn-block">
                                            <h4 class="lean-h"> Customer</h4>
                                        </button>
                                    </a>
                                </div>

                                
                                    <div class="col-lg-12">
                                  
                                       <label style="visibility:hidden">submit</label>
                                      
                                       <a href="{{url_for('main.loginvendor')}}">
                                         <button type="submit" class="btn btn-primary btn-block">
                                        <h4 class="lean-h">Vendor</h4>
                                       </button>
                                    </a>
                                   </div>
                               
                                   <div class="col-lg-12">
                                    

                                        <label style="visibility:hidden">submit</label>
                                        <a href="{{url_for('main.loginadmin')}}">
                                        <button type="submit" class="btn btn-primary btn-block">
                                            <h4 class="lean-h">Admin</h4>
                                        </button></a>
                                    </div>
                               </div>     
                        
							
						</div>
					</div>
				</div>
			</div>
			<!--
			<div class="row t20">
				<div class="col-lg-4 col-lg-offset-4">
					<div class="panel panel-default">
						<div class="panel-body">
							<form action="" method="POST" role="form">
							
								<div class="form-group">
									<label><i class="glyphicon glyphicon-plus-sign"></i> Add New Date</label>
									<div class="input-group">
									  <input type="date" class="form-control" placeholder="Select New Date" aria-label="date" aria-describedby="add-btn">
									  <span class="input-group-btn">
										<button type="submit" class="btn btn-primary" id="add-btn">
										  <i class="glyphicon glyphicon-plus-sign"></i> Add Date
										</button>
									  </span>
									</div>
								</div>
							
							</form>	
						</div>
					</div>
				</div>
			</div>-->

			

			<footer>
				<div class="row pad">
					<div class="col-lg-12 text-center">
						Copyright &copy; 2022 <strong>UBC SUO: Skip the line</strong>
					</div>
				</div>
			</footer>

		</div>


		<!-- jQuery -->
		<script src="{{url_for('static', filename='/bs/js/jquery.min.js')}}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{url_for('static', filename='/bs/js/bootstrap.min.js')}}"></script>
	</body>
</html>

foodtracker/templates/onthebudget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
	<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{url_for('static', filename='bs/css/united.min.css')}}" />
		<link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>
<body>

	<div class="container-fluid" id="wrapper">
			
		<div class="row" id="homeJumbo">
			<div class="overlay"></div>
			<div class="col-lg-12">
				<h1>
					<a href="{{url_for('main.index')}}">Skip the line</a>
				</h1>
				
				<div class="row t20">
					<div class="col-lg-4 col-lg-offset-4">
						<ul class="nav nav-pills nav-justified" >
						  <li role="presentation" >
							  <a href="{{url_for('main.index')}}" title="Home">Home</a>
						  </li>
		
						
						  <li role="presentation"  >
							<a href="{{url_for('main.cart')}}" title="Add Food Item"><i class="glyphicon glyphicon-shopping-cart"></i></a>
						</li>
                        <li role="presentation" class="active" >
							<a href="{{url_for('main.budget')}}" title="On the budget?">On the budget?</a>
						</li>
                    </li><li role="presentation"  >
                        <a href="{{url_for('main.protein')}}" title="Protein">Protein</a>
                    </li>
						<li role="presentation" >
							<a href="{{url_for('main.login')}}" title="Log out">Log out</a>
						</li>
						</ul>
				
					</div>

					
				</div>
			</div>
		</div>

			
        <div class="row t20">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <h3 class="lean-h text-black">
                            <i class="glyphicon glyphicon-piggy-bank"></i> On the budget?
                        </h3>
                        <h5 class="lean-h text-black">
                             Here is a recipe you can make at home!
                        </h5>
                        <hr />

                            
                            
                        <div class="list-group">
                            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
                              <div class="d-flex w-100 justify-content-between">
                                <h3 class="mb-1">{{title}}</h3>
                               
                              </div>
                              <p class="mb-1">{{servings}}</p>
                              <p class="mb-1">{{preptime}}</p>
                            </a>
                            <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
                              <div class="d-flex w-100 justify-content-between">
                                 <img src={{link}} alt="Recipe image" >
                              </div>
                             
                              <p class="mb-1"></p>
                              <pre class="mb-1">{{ingredients}}</pre>  
                              <pre class="mb-1">{{instructions}}</pre> 
                             
                                  
                                <label style="visibility:hidden">submit</label>
                               
                                <a href="{{url_for('main.budget')}}">
                                  <button type="submit" class="btn btn-primary btn-block">
                                 <h4 class="lean-h">Get another recipe</h4>
                                </button>
                             </a>
                       
                            </a>
                          </div>   
                    
                        
                    </div>
                </div>
            </div>
        </div>
			<!-- jQuery -->
		<script src="{{url_for('static', filename='/bs/js/jquery.min.js')}}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{url_for('static', filename='/bs/js/bootstrap.min.js')}}"></script>

</body>
</html>

foodtracker/templates/protein.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
	<link href="https://fonts.googleapis.com/css?family=Oswald|Ubuntu:400,700" rel="stylesheet">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{{url_for('static', filename='bs/css/united.min.css')}}" />
		<link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}" />

		<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>
<body>

	<div class="container-fluid" id="wrapper">
			
		<div class="row" id="homeJumbo">
			<div class="overlay"></div>
			<div class="col-lg-12">
				<h1>
					<a href="{{url_for('main.index')}}">Skip the line</a>
				</h1>
				
				<div class="row t20">
					<div class="col-lg-4 col-lg-offset-4">
						<ul class="nav nav-pills nav-justified" >
						  <li role="presentation" >
							  <a href="{{url_for('main.index')}}" title="Home">Home</a>
						  </li>
		
						
						  <li role="presentation"  >
							<a href="{{url_for('main.cart')}}" title="Add Food Item"><i class="glyphicon glyphicon-shopping-cart"></i></a>
						</li>
                        <li role="presentation"  >
							<a href="{{url_for('main.budget')}}" title="On the budget?">On the budget?</a>
						</li><li role="presentation" class="active" >
							<a href="{{url_for('main.protein')}}" title="Protein">Protein</a>
						</li>
						<li role="presentation" >
							<a href="{{url_for('main.login')}}" title="Log out">Log out</a>
						</li>
						</ul>
				
					</div>

					
				</div>
			</div>
		</div>

	
			
        <div class="row t20">
            <div class="col-lg-8 col-lg-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body text-center">
                        <h3 class="lean-h text-black">
                            <i class="glyphicon glyphicon-cutlery"></i> Find the amount of protein in food!
                        </h3>
                        
                        <hr />

                            
                            
                        <form class="form-group" action="/protein" method="post">
							<div class="row t20">
								<div class="col-lg-4 col-lg-offset-4">
									<div class="panel panel-default">
										<div class="panel-body text-center">
											<h3 class="lean-h text-black">
												 Search for food
											</h3>
											<hr />
				
												
												
												<div class="row">
													
				
												
													
				
												   <div class="col-lg-12">
													
														<br>
														  <input type="text" class="form-control" id="food-name" name="searchfood" placeholder="Searh for food" autofocus>
													
													</div>
													
											   
												   <div class="col-lg-12">
													
				
														<label style="visibility:hidden">submit</label>
														<a href="{{url_for('main.protein')}}">
														<button type="submit" class="btn btn-primary btn-block">
															<h4 class="lean-h">Search</h4>
														</button></a>
													</div>
											   </div>     
										
											
										</div>
									</div>
								</div>
							</div>
							</form>
							{% for i in listitems %}
								<pre> {{i}}</pre>
							{% endfor %}
                    
                        
                    </div>
                </div>
            </div>
        </div>
			<!-- jQuery -->
		<script src="{{url_for('static', filename='/bs/js/jquery.min.js')}}"></script>
		<!-- Bootstrap JavaScript -->
		<script src="{{url_for('static', filename='/bs/js/bootstrap.min.js')}}"></script>

</body>
</html>